### ISSUE TITLE
Nekopara Video File Corruption

### ISSUE THREAD

**Issue by nonosonic** [xmoeproject/KrkrExtract#4]
Extracted video files from the adultsonly.xp3 can not be played.

(Video files from data.xp3 are fine though in comparison.)

**Comment by marcussacana** [comment]
AMV movies not is a normal movie file...
for me is a movie AYUV or ARGB... but is not corrupted, if you know a program to read this file, contact-me plz, i like a way to open this movie

**Comment by nonosonic** [comment]
Are you sure it's not faulty in some way? 
VLC Media Player is supposed to be able to play AMV files but these it can't.

**Comment by nonosonic** [comment]
Should of checked this before but same problem for Vol 1

**Comment by marcussacana** [comment]
Not is corrupted, try delete of nekopara packget and check h-scenes animation...

**Comment by xmoeproject** [comment]
The krkr's amv is different from a normal amv file.
They just have the same extension name.

Here are some useful information:
#pragma pack(1)

typedef struct AlphaMovieInfo
{
	ULONG          Magic;
	ULARGE_INTEGER Version; //must be zero
	ULARGE_INTEGER FirstFrameOffset; //QuantaizationTableSize = Offset - sizeof(Header)
	ULONG          FrameCount;
	ULONG          FrameRateSecAtom;
	ULONG          FrameRatePerSec;
	USHORT         Width;
	USHORT         Height;
	ULONG          Attribute; //must be 1(JPG) or 2(Zlib)
} _AlphaMovieInfo, *pAlphaMovieInfo; 
//QuantaizationTable = Haffman + DCT

//@10016C30
//12 Seek

//24
typedef struct FrameHeaderZlib
{
	ULONG Magic;
	ULONG FrameSize; //实际是接在这之后数据的长度，包含0x10部分头部长度: FrameSize - 0x10 = CompSize * 4
	ULONG FrameIndex;
	WORD  Unk1;
	WORD  Unk2;
	WORD  BlockX;
	WORD  BlockY; //BlockX * BlockY = OriSize(Zlib, Alpha)
	ULONG CompSize;
}_FrameHeaderZlib, *pFrameHeaderZlib;


//20, No Comp Size
typedef struct FrameHeaderJPG
{
	ULONG Magic;
	ULONG FrameSize;
	ULONG FrameIndex;
	WORD  Unk1;
	WORD  Unk2;
	WORD  BlockX;
	WORD  BlockY; //BlockX * BlockY * 4 = OriSize
}_FrameHeaderJPG, *pFrameHeaderJPG;

#pragma pack()

//===========================
struct FrameHolder
{
	ULONG Unk1;   //和FrameHeader中的一样
	ULONG Unk2;   //和FrameHeader中的一样
	ULONG BlockX; //和FrameHeader中的一样
	ULONG BlockY; //和FrameHeader中的一样
	PVOID FrameBuffer; //BlockX * BlockY * 4
	ULONG FrameSize; //和FrameHeader中的一样

	FrameHolder(ULONG args1,
				ULONG args2,
				ULONG mBlockX,
				ULONG mBlockY,
				ULONG mFrameSize
		) :
		Unk1(args1),
		Unk2(args2),
		BlockX(mBlockX),
		BlockY(mBlockY),
		FrameSize(mFrameSize),
		FrameBuffer(nullptr)
	{
		FrameBuffer = HeapAlloc(GetProcessHeap(), 0, BlockX * BlockY * 4);
	}
};

There is little point in analysing an amv file directly because I have a very simple to dump it:
https://github.com/xmoeproject/AlphaMovieDecoder
