### ISSUE TITLE
Repacking problem

### ISSUE THREAD

**Issue by knatum97** [xmoeproject/KrkrExtract#64]
I'm doing a repack for Re:LieF ～親愛なるあなたへ～, so I unpacked the data.xp3 using krkrextract. by default, all the files inside the xp3 are categorized into sub folders depending on character and file type, but whenever I try to repack the program automatically excludes all sub folders and their contents. 

Is there a way for me to get the program to include subfolder contents as well?

PS: Additionally, I'm getting an issue that reads: 
"Couldn't open: LoadThumbnail.tjs "during repacking

**Comment by marcussacana** [comment]
Friend, in the case of this game I think is useless you repack it.
The Re:LieF contains a single .xp3 storing the entire game files,
If you modify anything you will need upload the entire game basically,
Since I by what I remember he don't search for the patch.xp3

Then it's useless you repack the .xp3, It's more easy you remove the encryption plugin
and repack the .xp3 decrypted.
