### ISSUE TITLE
Cafe Stella to Shinigami no Chou

### ISSUE THREAD

**Issue by KiritoCy** [xmoeproject/KrkrExtract#72]
Can you please update KrkrExtract, to fully support Yuzusoft's newest release Cafe Stella to Shinigami no Chou?
https://vndb.org/v26414

While latest version seems to be able to extract things at some extent from the latest updated .xp3 archives, when i try to extract its scripts they're still encrypted, also the 'PsbTextDumperV2' while it converts the .ks.scn scripts into .txt for some weird reason only the character names appear in the scripts while the lines are not there. 
(Yeah, everytime Yuzusoft has new VN new Updated KiriKiri Engine comes with it ;p)

**Comment by xmoeproject** [comment]
You should use psb decompiler instead of "PsbTextDumperV2", which is out of date

**Comment by KiritoCy** [comment]
Thanks for the fast reply and..... Sry, i'm kinda low on this things tbh despite of how MANY scripts i've dealt with and converted them to txt. I only managed to make things work out when good people i've given precise instructions on how to work with such stuff, so long story short idk what to do it's kinda embarassing ;s

**Comment by xmoeproject** [comment]
make sure "Decompile script" is selected.
![image](https://user-images.githubusercontent.com/10909416/71305814-f57fe680-2413-11ea-88b4-cf7c15a36abc.png)

all psb files can be decompiled into json format
![image](https://user-images.githubusercontent.com/10909416/71305810-ec8f1500-2413-11ea-9898-76eaaf10114c.png)

because the structure of the script can be an arbitrary format, so we should extract the scene script case by case.

**Comment by KiritoCy** [comment]
Hmm, everything i try apart from selecting only Raw it makes it crash while saying 'Failed to decompress special chuck'.

**Comment by xmoeproject** [comment]
try to update KrkrExtract to the latest version, it works on my machine.

**Comment by KiritoCy** [comment]
Finally, i actually managed to do it, bless you man, thanks a lot! Gotta love it when people actually respond and keep such good tools up to date while giving you the actual advice you need. ;D
